# Generated by Django 5.2.1 on 2025-05-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citysearch',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
